# Generated by Django 5.0 on 2024-04-19 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0003_circle_operator_os_test1"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test1",
        ),
    ]
